application:
  env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ignitedb
    username: ignite
    password: ignite
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true